import Head from "next/head";
import PopupModel from "../src/popupModel";
import { useEffect, useState } from "react";
import axios from "axios";
import AnimatedCursor from "react-animated-cursor";
import Image from "next/image";
export default function Home() {
  const [displayPopup, setDisplayPopup] = useState(false);
  const [email, setEmail] = useState("");
  const [error, setError] = useState(false);
  const [pageLoaded, setpageLoaded] = useState(false);
  const [popupErrorMessage, setPopupErrorMessage] = useState("");

  useEffect(() => {
    setpageLoaded(true);
    window.addEventListener("contextmenu", (e) => e.preventDefault());
  }, []);

  useEffect(() => {
    if (error)
      if (email && /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(email))
        setError(false);
      else setError(true);
  }, [email]);

  const handleSubmit = (e) => {
    if (email && /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(email)) {
      setError(false);
      axios
        .post("/api/email", {
          email,
        })
        .then((res) => {
          setEmail("");
          setDisplayPopup(true);
        })
        .catch((err) => {
          console.log({ err: err.response.data });
          setDisplayPopup(true);
          if ("Email already exist" === err.response.data)
            setPopupErrorMessage("already");
        });
    } else {
      setError(true);
    }
  };
  return (
    <div>
      {pageLoaded && <AnimatedCursor color={"0, 0, 0"} />}
      <Head>
        <title>JUST Law Courses [JSL]</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen flex flex-col items-center justify-center">
        <section
          style={{ minWidth: "300px" }}
          className=" px-16 pt-7 pb-4 m-2 md:w-auto w-[300px] sm:w-96 rounded-lg border-2 border-black bg-white text-center"
        >
          {/* <h1 className="text-7xl md:text-9xl font-bold ">JUST</h1>
          <h2 className="text-3xl md:text-5xl font-bold">LAW SCHOOL</h2> */}
          <Image
            src={"/asserts/image/jls.webp"}
            alt="jls"
            width={340}
            height={170}
          />
        </section>
        <p className="text-lg md:text-2xl text-center m-3 md:m-5">
          Everything about legal education <br /> is about to change
        </p>
        <div className="w-auto">
          <div className="flex-col sm:flex-row flex ">
            <input
              style={{ minWidth: "300px" }}
              className={`text-center sm:text-left pl-6 sm:w-96 border-2 border-black rounded sm:rounded-br-none sm:rounded-tr-none w-full p-1 ${
                error ? "border-red-500 bg-red-100" : ""
              }`}
              placeholder="E-mail address"
              onChange={(e) => {
                setEmail(e.target.value);
              }}
              onKeyDown={(e) => {
                console.log(e.key);
                if (e.key === "Enter") handleSubmit();
              }}
              required
              value={email}
              type={"email"}
            />
            <PopupModel
              onClick={handleSubmit}
              displayPopup={displayPopup}
              hidePopup={() => setDisplayPopup(false)}
              popupErrorMessage={popupErrorMessage}
              className="px-4 border-l-0 bg-black text-white border-2 border-black rounded mt-1 w-full sm:w-auto sm:mt-0 sm:rounded-bl-none sm:rounded-tl-none min-w-fit p-1 "
            >
              Apply for <span className="font-bold">Early Access</span>
            </PopupModel>
          </div>
          {error && (
            <p className="text-red-500 text-center sm:text-left ml-2">
              Enter valid email address{" "}
            </p>
          )}
        </div>
      </div>
    </div>
  );
}
